---
abstract: 'xml schema (xsd) converter to relational database  objects (database supported are oracle and postgresql); xml put and get from/to the database'
author:
  - 'lorenzo bellotti <pauseblx@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: blx-xsdsql
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 1.58
  Test::Database: 1.11
  XML::Parser: 1.21
  XML::Writer: 0.600
version: 0.009003
