this is a string

/* generated by blx::xsd2sql */

alter table ROOT_xml_3 add constraint ROOT_xml_3_pk primary key (ID);
alter table Types add constraint Types_pk primary key (ID);

/* end of  blx::xsd2sql */

