this is a string

/* generated by blx::xsd2sql */

create table ROOT_xml_3( /* PATH: / */
	ID	numeric(18)	
	,Types	numeric(18)	/*  REF: /Types */
);

create table Types( /* PATH: /Types */
	ID	numeric(18)	
	,float	float	/* PATH: /Types/float */
	,double	double precision	/* PATH: /Types/double */
	,decimal	decimal	/* PATH: /Types/decimal */
	,integer	numeric	/* PATH: /Types/integer */
	,nonPositiveInteger	numeric	/* PATH: /Types/nonPositiveInteger */
	,negativeInteger	numeric	/* PATH: /Types/negativeInteger */
	,long_	numeric	/* PATH: /Types/long */
	,int_	numeric	/* PATH: /Types/int */
	,short_	numeric	/* PATH: /Types/short */
	,byte_	numeric	/* PATH: /Types/byte */
	,nonNegativeInteger	numeric	/* PATH: /Types/nonNegativeInteger */
	,unsignedLong	numeric	/* PATH: /Types/unsignedLong */
	,unsignedInt	numeric	/* PATH: /Types/unsignedInt */
	,unsignedShort	numeric	/* PATH: /Types/unsignedShort */
	,unsignedByte	numeric	/* PATH: /Types/unsignedByte */
	,positiveInteger	numeric	/* PATH: /Types/positiveInteger */
	,dateTime	varchar(50)	/* PATH: /Types/dateTime */
	,date_	varchar(50)	/* PATH: /Types/date */
	,time	varchar(50)	/* PATH: /Types/time */
	,gYear	varchar(50)	/* PATH: /Types/gYear */
	,gYearMonth	varchar(50)	/* PATH: /Types/gYearMonth */
	,gMonthDay	varchar(50)	/* PATH: /Types/gMonthDay */
	,duration	varchar(4096)	/* PATH: /Types/duration */
	,I0	varchar(4096)	/* PATH: /Types/ID */
	,IDREF	varchar(4096)	/* PATH: /Types/IDREF */
	,IDREFS	varchar(4096)	/* PATH: /Types/IDREFS */
	,NMTOKEN	varchar(4096)	/* PATH: /Types/NMTOKEN */
	,NMTOKENS	varchar(4096)	/* PATH: /Types/NMTOKENS */
	,language	varchar(4096)	/* PATH: /Types/language */
	,Name	varchar(4096)	/* PATH: /Types/Name */
	,QName	varchar(4096)	/* PATH: /Types/QName */
	,NCName	varchar(4096)	/* PATH: /Types/NCName */
	,string	varchar(4096)	/* PATH: /Types/string */
	,normalizedString	varchar(4096)	/* PATH: /Types/normalizedString */
	,token	varchar(4096)	/* PATH: /Types/token */
	,base64Binary	varchar(4096)	/* PATH: /Types/base64Binary */
	,hexBinary	varchar(4096)	/* PATH: /Types/hexBinary */
	,boolean	boolean	/* PATH: /Types/boolean */
	,anyURI	varchar(4096)	/* PATH: /Types/anyURI */
);


/* end of  blx::xsd2sql */

